# Sample .travis.yml for R projects.
#
# Using standard travis R build env now
# from here: https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages

r:
  - oldrel
  - release
  - devel

#before_install:
#  - tlmgr install index
  
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"