# Sample .travis.yml for R projects.
#
# Using standard travis R build env now
# from here: https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages

r:
  - oldrel
  - release
  - devel


